version: "3"

services:
  auth:
    build: ./auth
    environment:
      - POSTGRES_DSN=postgres://user:pa$$word@auth_db
    ports:
      - '8000:8000'
    depends_on:
      - "auth_db"

  auth_db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pa$$word
    ports:
      - '5432:5432'
    volumes:
      - auth_db:/var/lib/postgresql/data
volumes:
  auth_db:
    driver: local
