version: "3"

x-common-variables:
  &common-variables
  AUTH_PUBLIC_KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDZW73XZ6aUAP6JdJpW0Ktk/3Ye2dw6cMCwWaz8EeRJ+iSdurK67d4RtcqDW0t2idwUvqq9Idd8WX6EDJMpMKRb6ViamOUQ7EvswHVrGvfk8RIQQuyrNXrH/YsIHkLLjPxnmNnFtKhnAEQA0mewzOpJs3x/3ttQrHPCHtbTaTdxoIlL8UQM2iuWCgLHrzVcMje3GyQ++xmjCusjsYFJEQYhCCAU+6opQl4oExa/Umu915ERKAU07MyLwFvRZQ6KJMR3Qkmzrcx0sG3pO6hWDYPr3mYch9/kdt+LKefDV9TQDyZl8hBKSVQwFPn4aVe9xvtw7s6XlBzfPvRDAPXj7ucQ+a6c3Wx8z+4n/9iMpjAgaZRMktLncR+eIAuDiH0uIrAJijqPUDBU9HhCXiwQAiL6iRziA8arXrfQmuoaajIB9+y4ZuCOWmp8I73GHAh3wDvKdkDAoKakSu4rgqA0cmJ8Ik/XI9G9S9AqELo9vKa90Jo2yhHo2RHplrxt4LrsqKTQkofp7cpwJOcqldEma248aJHkjLwl8+UlBdugZgO3sv5ji3pdMKKQ37T1CGB50lVIWq+15QgmjPjHR9nEvt/c99PP/cyyePv3KBkkl4LfSUv6q1GKIwZmZBYabhVJ60xiWidVhWXcpy5qY6+osaNHsA10v4HZk2qMQhsQA8nJjw== ameyarao98@zenbook-manjaro

services:
  auth:
    build: ./auth
    restart: on-failure
    environment:
      <<: *common-variables
      POSTGRES_DSN: postgres://user:pa$$word@auth_db
      PYTHONHASHSEED: 0
    ports:
      - '8000:8000'
    depends_on:
      - "auth_db"

  auth_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa$$word
    ports:
      - 5433:5432
    volumes:
      - auth_db:/var/lib/postgresql/data

  factory:
    build: ./factory
    restart: on-failure
    environment:
      POSTGRES_DSN: postgres://user:pa$$word@factory_db
    ports:
      - '8080:8080'
    depends_on:
      - "factory_db"

  factory_db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pa$$word
    ports:
      - 5434:5432
    volumes:
      - factory_db:/var/lib/postgresql/data

  controller:
    build: ./controller
    restart: on-failure
    environment:
      <<: *common-variables
    ports:
      - '3000:3000'

volumes:
  auth_db:
    driver: local
  factory_db:
    driver: local
