// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Resource struct {
	Name        string  `json:"name"`
	Probability float64 `json:"probability"`
	Color       string  `json:"color"`
}
